### PR TITLE
PR corresponding with issue #1

### PR DESCRIPTION
**Pull request by yo1995**
With [this issue](https://github.com/nguyenvanduocit/Wox.Plugin.Emoji/issues/1).

Added colored icon support with Microsoft Emoji png files.

To test you could download the .dll in released folder, the whole icons folder and replace the original ones under plugin directory.

More to accomplish by you: 
- reorganize files and add /Icons to release version
- change version number and submit to Wox plugin wpm

😄 have a nice weekend.

### CODE REVIEW

**Comment by lnunno** [comment]
Any chance on this getting merged?

@yo1995 @nguyenvanduocit

**Comment by yo1995** [comment]
> Any chance on this getting merged?
> 
> @yo1995 @nguyenvanduocit

hmmm seems that Duoc is not responding... anyway I'm pretty sure this PR works for me. 
If you'd like to use it you can just replace the .dll with https://github.com/yo1995/Wox.Plugin.Emoji/tree/master/Released , and also paste in the icons with https://github.com/yo1995/Wox.Plugin.Emoji/tree/master/Icons

**Comment by lnunno** [comment]
@yo1995 Might be worth publishing your fork also so it's easy to install, maybe just slightly change the name.

**Comment by yo1995** [comment]
> @yo1995 Might be worth publishing your fork also so it's easy to install, maybe just slightly change the name.

OK I'll wait until 2~3 weeks later to see if he merge this one. If not I'll do my own version.

**Comment by yo1995** [comment]
@lnunno Merged! Thank you Duoc~ 😄

**Pull request merged**
